always_for_in = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
annotate_untyped_fields_with_any = false
format_docstrings = true
conditional_to_if = true
margin = 92
separate_kwargs_with_semicolon = true
