name = "RAITest"
uuid = "c631b9c8-0012-4e76-a6f8-6f70f8f987b9"
authors = ["Martin McGrane <martin.mcgrane@relational.ai> and contributors"]
version = "0.1.0"

[deps]
RAI = "9c30249a-7e08-11ec-0e99-a323e937e79f"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
