name: 'Setup RAICloud'
description: 'Set up RAICloud credentials'

inputs:
  environment:
    required: true
    description: 'Environment name'

  client_id:
    required: true
    description: 'Client ID'

  client_secret:
    required: true
    description: 'Client secret'

  profile:
    required: false
    description: 'RAICloud profile name'

runs:
  using: "composite"
  steps:
    - run: mkdir -p $HOME/.rai
      shell: bash

    - run: |
        echo -e "[${{ inputs.profile || inputs.environment }}]\n" >> $HOME/.rai/config
        echo -e "region=us-east\n" >> $HOME/.rai/config
        echo -e "infra=azure\n" >> $HOME/.rai/config
        echo -e "port=443\n" >> $HOME/.rai/config
        echo -e "host=azure-${{inputs.environment}}.relationalai.com\n" >> $HOME/.rai/config
        echo -e "client_credentials_url=https://relationalai-${{inputs.environment}}.us.auth0.com/oauth/token\n" >> $HOME/.rai/config
        echo -e "client_id=${{ inputs.client_id }}\n" >> $HOME/.rai/config
        echo -e "client_secret=${{ inputs.client_secret }}\n" >> $HOME/.rai/config
      shell: bash
